### ISSUE TITLE
Review Blatt 01

### ISSUE THREAD

**Issue by ManuelHertle** [ManuelHertle/Haskell-01#3]
to review

**Comment by ManuelHertle** [comment]
Ich bin mir nicht sicher, ob ich Sie als Colaborateur einladen musste damit ich eine Issue zuteilen konnte. Ich habe es nur so hingekriegt.

**Comment by mgudemann** [comment]
Ja, das geht tatsächlich nur so. Die weiteren Aufgaben sind allerdings per github classroom, da ist das kein Problem mehr.

**Comment by mgudemann** [comment]
der Property Test funktioniert leider nicht, da negative Zahlen nicht richtig unterstützt werden. Dabei wird der Basisfall der Rekursion nicht eintreten und die Funktion terminiert nicht.
